### ISSUE TITLE
click push button then Unity dies.

### ISSUE THREAD

**Issue by sevelee** [github-beta/unity-preview#7] opened 2017-04-13 05:23 UTC
Please fill out the data below and inc
[github-unity.log.zip](https://github.com/github-beta/unity-preview/files/918558/github-unity.log.zip)
lude a zip with the Unity log file and the extension log file.
On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnityDebug\github-unity.log`
On macOS, the extension log file is at `~/.local/share/GitHubUnityDebug/github-unity.log`

If you prefer not to submit your log files through the issue tracker, send them
to unity@github.com with the issue number.

Version of Unity (eg. 5.5.0f1): 5.5.2f1
Version of GitHub for Unity (see console output): 0.8 alpha
Platform (eg. Windows, macOS, Linux): macOS

What happened
I followed the steps and finished setting the Github with unity. 
When I click the push button, a window showing "git push" shows up then nothing.
And the unity goes into freeze.

**Comment by StanleyGoldman** [comment] 2017-04-13 18:36
Hey @sevelee, thanks for trying.
We should have this figured out by the next time we 🚢.

**Comment by StanleyGoldman** [comment] 2017-04-13 18:36
Duplicate of #5

**Comment by shana** [comment] 2017-04-20 16:54
Tracking this one in #5

**Closed as completed by shana** 2017-04-20 16:54 UTC
Labels: bug, duplicate
