### ISSUE TITLE
Warning in Unity Console

### ISSUE THREAD

**Issue by jessemcculloch** [github-beta/unity-preview#6] opened 2017-04-13 01:41 UTC
Version of Unity (eg. 5.5.0f1): 5.5.2f1
Version of GitHub for Unity (see console output): 0.8.0.0 
Platform (eg. Windows, macOS, Linux): Windows

I am seeing the following error in the Unity Console whenever I exit play mode -

> Serialization depth limit 7 exceeded at 'FileTreeNode.children'. There may be an object composition cycle in one or more of your serialized classes.
> 
> Serialization hierarchy:
> 8: FileTreeNode.children
> 7: FileTreeNode.children
> 6: FileTreeNode.children
> 5: FileTreeNode.children
> 4: FileTreeNode.children
> 3: FileTreeNode.children
> 2: GitHub.Unity::ChangesetTreeView.tree
> 1: GitHub.Unity::ChangesView.tree
> 0: GitHub.Unity::Window.changesTab

[github-unity.zip](https://github.com/github-beta/unity-preview/files/918309/github-unity.zip)

**Comment by StanleyGoldman** [comment] 2017-04-13 18:35
Thanks for the bug report @jessemcculloch.
I think I have the cause for that issue wrapped up.
We will let you know when we 🚢 the next update.

**Comment by shana** [comment] 2017-04-20 20:17
Fixed in 0.9.1-alpha!

**Closed as completed by shana** 2017-04-20 20:17 UTC
Labels: bug
