### ISSUE TITLE
Unable to commit changes, 

### ISSUE THREAD

**Issue by GeorgeZZZZZ** [github-beta/unity-preview#34] opened 2017-04-29 15:16 UTC
21:02:18 PM WARN [ 2] <GitInstaller>                      Archive "PlatformResources\windows\git-lfs.zip" missing
21:05:58 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
21:05:58 PM INFO [ 1] <LoginManager>                      Login Username:GeorgeZZZZZ
21:06:02 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
21:12:01 PM ERROR [ 3] <TaskRunner>                        
Task_Start_ContinuationTask
  at System.Threading.Tasks.Task.Start (System.Threading.Tasks.TaskScheduler scheduler) [0x00000] in <filename unknown>:0 
  at GitHub.Unity.BaseTask.Run (CancellationToken cancellationToken) [0x00024] in D:\code\github\UnityInternal\src\GitHub.Api\Tasks\BaseTask.cs:87 
  at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3 () [0x00000] in D:\code\github\UnityInternal\src\GitHub.Api\Tasks\TaskRunnerBase.cs:218 
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex, System.String message) in D:\code\github\UnityInternal\src\GitHub.Logging\LogAdapterBase.cs:line 168
   at GitHub.Unity.LogAdapterBase.Error(System.Exception ex) in D:\code\github\UnityInternal\src\GitHub.Logging\LogAdapterBase.cs:line 174
   at GitHub.Unity.TaskRunnerBase.<RunLoop>m__3() in D:\code\github\UnityInternal\src\GitHub.Api\Tasks\TaskRunnerBase.cs:line 222
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TaskExecuteWaitCallback(System.Object obj)
21:14:58 PM WARN [ 1] <RepositoryWatcher>                 Watcher already stopped
21:15:23 PM INFO [ 1]                                     Initializing GitHub for Unity version 0.10.0.0
21:21:54 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
21:21:54 PM INFO [ 1] <LoginManager>                      Login Username:GeorgeZZZZZ
21:22:08 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
21:26:48 PM WARN [ 1] <RepositoryWatcher>                 Watcher already stopped
21:27:34 PM INFO [ 1]                                     Initializing GitHub for Unity version 0.10.0.0
21:28:39 PM WARN [ 1] <RepositoryWatcher>                 Watcher already stopped
21:29:18 PM INFO [ 1]                                     Initializing GitHub for Unity version 0.10.0.0
21:30:01 PM INFO [ 1]                                     Initializing GitHub for Unity version 0.10.0.0
21:34:26 PM INFO [ 1]                                     Initializing GitHub for Unity version 0.10.0.0
22:02:28 PM INFO [ 1]                                     Initializing GitHub for Unity version 0.10.0.0
22:10:48 PM ERROR [ 2] <GitCredentialManager>              Failed to get the credential helper
22:17:03 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
22:17:03 PM INFO [ 1] <LoginManager>                      Login Username:GeorgeZZZZZ
22:18:53 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
22:22:10 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
22:22:10 PM INFO [ 1] <LoginManager>                      Login Username:pknlm789@gmail.com
22:22:19 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
22:22:31 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
22:22:31 PM INFO [ 1] <LoginManager>                      Login Username:pknlm789@gmail.com
22:29:28 PM WARN [ 1] <LoginManager>                      Login Exception
TaskCanceledException_ctor_DefaultMessage
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[Octokit.ApplicationAuthorization].GetResult () [0x00000] in <filename unknown>:0 
  at GitHub.Unity.LoginManager+<Login>c__async0.MoveNext () [0x00164] in D:\code\github\UnityInternal\src\GitHub.Api\Authentication\LoginManager.cs:90 
   at GitHub.Unity.LogAdapterBase.Warning(System.Exception ex, System.String message) in D:\code\github\UnityInternal\src\GitHub.Logging\LogAdapterBase.cs:line 140
   at GitHub.Unity.LoginManager+<Login>c__async0.MoveNext() in D:\code\github\UnityInternal\src\GitHub.Api\Authentication\LoginManager.cs:line 126
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object stateMachine)
   at System.Security.SecurityContext.Run(System.Security.SecurityContext securityContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Security/SecurityContext.cs:line 150
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Threading/ExecutionContext.cs:line 150
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Runtime.CompilerServices.TaskAwaiter+<>c__DisplayClassa.<OnCompletedInternal>b__1(System.Object state)
   at GitHub.Unity.MainThreadSynchronizationContext+<Post>c__AnonStorey1.<>m__0() in D:\code\github\UnityInternal\src\UnityExtension\Assets\Editor\GitHub.Unity\Threading\SingleThreadSynchronizationContext.cs:line 25
   at UnityEditor.EditorApplication.Internal_CallDelayFunctions() in C:\buildslave\unity\build\artifacts\generated\common\editor\EditorApplicationBindings.gen.cs:line 259
22:29:41 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
22:29:41 PM INFO [ 1] <LoginManager>                      Login Username:pknlm789@gmail.com
22:31:37 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
22:33:31 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper
22:33:31 PM INFO [ 1] <LoginManager>                      Login Username:GeorgeZZZZZ
22:33:38 PM ERROR [ 1] <GitCredentialManager>              Failed to get the credential helper

Version of Unity : 5.6.0f3
Version of GitHub for Unity (see console output): 2.11.1.windows.1
Platform (eg. Windows, macOS, Linux): win 8.1

What happened:

1. Experience slow when switch to "changes" tab.
The unity become very slow. No matter I click on a button or type words, I need wait for a long time to get response.

2. Can't commit changes
After I select all and click on button "commit to master", the button will become gray for a wile. When the button change back, every thing remain same. It still shows I have same amount of changed files and nothing has changed in history tab.
Some time Unity freeze after I press the button.

3. Push nothing
Because I can't commit any changes, I try to push the initial commit. 
Some times git push widow will pop out but never end, if I cancel it then a login widow will pop out.
Some times git push widow will close but nothing happens in my repository.

**Comment by jessemcculloch** [comment] 2017-04-29 16:40
Are you checking the files off that you want committed? I was having the same issues, then realized I wasn't selecting the files I needed to commit

**Comment by GeorgeZZZZZ** [comment] 2017-04-30 13:13
Hi, what do you mean checking file off? 
Because if I don't check the files I want to commit, the commit button will be grey and can't be press.

I record a video for my operation steps.
[https://youtu.be/utQ2wLaOT08](url)

**Comment by StanleyGoldman** [comment] 2017-05-01 11:36
Hey @jessemcculloch thanks for helping and @GeorgeZZZZZ and thanks for being willing to make a video. We appreciate it.

**Comment by StanleyGoldman** [comment] 2017-05-01 13:42
Hey @GeorgeZZZZZ thanks for the video, it was really helpful.
This problem is a duplicate of #29. I'm going to close this out and track things there.

**Closed as completed by StanleyGoldman** 2017-05-01 13:42 UTC
Labels: bug, duplicate
